# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_load_offices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fiscal_year', models.IntegerField(verbose_name='fiscal year')),
                ('type', models.CharField(choices=[('A', 'Achievement'), ('I', 'Initiative')], max_length=1, verbose_name='achievement type')),
                ('description', models.TextField(verbose_name='description')),
                ('points', models.IntegerField(blank=True, help_text='Points assigned by supervisor. 0 to 5. 0 means not accepted, 5 means highest impact', null=True, verbose_name='points')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='employees.Employee', verbose_name='employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
