# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 15:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_project_office'),
        ('employees', '0002_load_offices'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('expectations', models.TextField(blank=True, null=True)),
                ('weight', models.FloatField(validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)])),
                ('fiscal_year', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Fiscal year must use format AFYY. For example AF16 for fiscal year 2016', regex='^AF\\d{2}$')])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_goals', to='employees.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ExpectationsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('expected_advancement', models.FloatField(default=0.9, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)])),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='goals')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employeegoal',
            name='expectations_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_goals', to='goals.ExpectationsList'),
        ),
        migrations.AddField(
            model_name='employeegoal',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_goals', to='goals.Goal'),
        ),
        migrations.AlterUniqueTogether(
            name='employeegoal',
            unique_together=set([('employee', 'goal', 'expectations_list')]),
        ),
    ]
