# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='expectations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
