# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 14:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_load_offices'),
        ('goals', '0002_goal_expectations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeegoal',
            name='fiscal_year',
        ),
        migrations.AddField(
            model_name='expectationslist',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expectationslist',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expectations_list', to='employees.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expectationslist',
            name='fiscal_year',
            field=models.CharField(default='AF00', max_length=4, validators=[django.core.validators.RegexValidator(message='Fiscal year must use format AFYY. For example AF16 for fiscal year 2016', regex='^AF\\d{2}$')]),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='expectationslist',
            unique_together=set([('version', 'employee', 'fiscal_year')]),
        ),
    ]
