# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-21 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
