# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-13 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20160813_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='milestone_type',
            field=models.CharField(choices=[('START', 'Start'), ('END', 'End'), ('OTHER', 'Other')], default='OTHER', max_length=5, verbose_name='Milestone type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to='employees.Employee', verbose_name='Project Manager'),
        ),
    ]
