# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_photo'),
        ('projects', '0003_auto_20160813_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('LEADER', 'Leader')], default='MEMBER', max_length=6)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='employees.Employee', verbose_name='Member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.Project', verbose_name='Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
