# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-27 12:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fiscal_year',
            field=models.CharField(default='AF00', max_length=4, validators=[django.core.validators.RegexValidator(message='Fiscal year must use format AFYY. For example AF16 for fiscal year 2016', regex='^AF\\d{2}$')]),
            preserve_default=False,
        ),
    ]
