# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_load_offices'),
        ('projects', '0005_project_fiscal_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='office',
        ),
        migrations.AddField(
            model_name='project',
            name='executing_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='employees.OrganizationUnit', verbose_name='excecuting office'),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.IntegerField(default=10, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='project',
            name='justification',
            field=models.TextField(blank=True, verbose_name='Justification'),
        ),
        migrations.AlterField(
            model_name='project',
            name='scope',
            field=models.TextField(blank=True, verbose_name='Scope'),
        ),
    ]
