# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import model_utils.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('company_id', models.CharField(blank=True, max_length=7, verbose_name='ACP IP')),
                ('first_name', models.CharField(max_length=60, verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, max_length=60, verbose_name='Middle name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last name')),
                ('username', models.CharField(max_length=35, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=120, verbose_name='Office name')),
                ('short_name', models.CharField(max_length=8, unique=True, verbose_name='Office Letters')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='employees.OrganizationUnit')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone number')),
                ('phone_type', models.CharField(choices=[('BUSINESS', 'Business'), ('MOBILE', 'Mobile'), ('HOME', 'Home'), ('RADIO', 'Radio'), ('OTHER', 'Other')], default='BUSINESS', max_length=8, verbose_name='Phone type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.OrganizationUnit', verbose_name='Office'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phones',
            field=models.ManyToManyField(related_name='owner', to='employees.Phone'),
        ),
    ]
