# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 13:31
from __future__ import unicode_literals

from django.db import migrations

from ..initial_data import create_acp_organization

def load_data(apps, schema_editor):
    create_acp_organization()


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
