# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_load_offices'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, upload_to='photos/'),
        ),
    ]
