# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='employees.Employee', verbose_name='Employee')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='employees.OrganizationUnit', verbose_name='Office')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
