# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-01 22:21
from __future__ import unicode_literals

from django.db import migrations

from ..initial_data import create_grades, create_pds


def load_data(apps, schema_editor):
    create_grades()
    create_pds()
    #create_positions()

class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
