# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_load_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionemployeeassignment',
            name='planned_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='positionemployeeassignment',
            name='planned_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
