# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('display_order', models.IntegerField(default=1, verbose_name='Diplay order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='projects.Project', verbose_name='Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
